#!/usr/bin/env lua

PATTERN = "\tusing boost::%s;"

type_prefixes = {
	"int";
	"int_least";
	"int_fast";
	"uint";
	"uint_least";
	"uint_fast";
}

additional_types = {
	"intmax_t";
	"uintmax_t";
}

main = function()
	LINES = {}

	insertLine(PREFIX)

	for _, bits in ipairs{8, 16, 32} do
		insertDeclaration(generateTypesForBitSize(bits))
	end

	insertLine("\n#ifndef BOOST_NO_INT64_T")
	insertDeclaration(generateTypesForBitSize(64))
	insertLine("#endif // ifndef BOOST_NO_INT64_T\n")

	insertDeclaration(additional_types)


	insertLine(SUFFIX)

	print(table.concat(LINES, "\n"))
end

generateTypesForBitSize = function(bits)
	local ret = {}
	for _, typebase in ipairs(type_prefixes) do
		table.insert(ret, ("%s%d_t"):format(typebase, bits))
	end
	return ret
end

insertLine = function(line)
	table.insert(LINES, line)
end

insertDeclaration = function(typename)
	if type(typename) == "table" then
		for _, t in ipairs(typename) do
			insertDeclaration(t)
		end
		return
	end
	insertLine(PATTERN:format(typename))
end

PREFIX = [[
/*
	@brief Header - AUTO-GENERATED BY generate_booststdint.lua

	Annoyed how boost/cstdint.hpp almost does everything you want, except
	it puts the types directly in the boost namespace so you can't do an
	easy "using namespace" line to import just the standard integers?

	Well, this header makes such a namespace: stdint.  All the tedious
	work is done for you (by the script that generated this file).

	@date 2012

	@author
	Ryan Pavlik
	<rpavlik@iastate.edu> and <abiryan@ryand.net>
	http://academic.cleardefinition.com/
	Iowa State University Virtual Reality Applications Center
	Human-Computer Interaction Graduate Program
*/

//          Copyright Iowa State University 2012.
// Distributed under the Boost Software License, Version 1.0.
//    (See accompanying file LICENSE_1_0.txt or copy at
//          http://www.boost.org/LICENSE_1_0.txt)

#pragma once
#ifndef INCLUDED_booststdint_h_GUID_96d717cd_827b_4889_8505_6a9102af0dae
#define INCLUDED_booststdint_h_GUID_96d717cd_827b_4889_8505_6a9102af0dae

// Internal Includes
// - none

// Library/third-party includes
#include <boost/cstdint.hpp>


// Standard includes
// - none

namespace stdint {
]]

SUFFIX = [[

} // end of namespace stdint

#endif // INCLUDED_booststdint_h_GUID_96d717cd_827b_4889_8505_6a9102af0dae
]]


main()
